name: SSH Deploy  

on:  
  push:  
    branches: [ main ]  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    environment: production  

    steps:  
      - name: Checkout  
        uses: actions/checkout@v2  

      # 设置SSH代理  
      - name: Start ssh-agent  
        run: |  
          mkdir -p ~/.ssh  
          ssh-agent -a $SSH_AUTH_SOCK >~/.ssh/agent.$GITHUB_RUN_ID.log 2>&1  
          ssh-add -D  
          echo "$SSH_PRIVATE_KEY" | ssh-add - >~/.ssh/id_rsa  

          # 你可以在这里添加更多的SSH命令或脚本  
          # 例如，
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'ls -la'  

      env:  
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}  

      # 注意：出于安全考虑，上面的SSH命令是注释掉的。  
      # 你应该使用脚本来处理SSH连接和命令执行，  
      # 并确保你的私钥不会以明文形式出现在日志中。  

      # 清理SSH代理  
      - name: Stop ssh-agent  
        if: always()  
        run: |  
          ssh-agent -k  
          rm -f ~/.ssh/agent.$GITHUB_RUN_ID.log  
          rm -f ~/.ssh/id_rsa
