name: SSH-Password

on:
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Execute SSH Commands
        run: |
          sshpass -p "Vpn123123" ssh -o StrictHostKeyChecking=no rtian001@s1.ct8.pl << 'EOF'
            echo "Running commands on remote server"
            whoami
            # 其他您想执行的命令
          EOF